//
//  Login2Wireframe.swift
//  EMFRAME
//
//  Created by Mohammad Kukuh on 8/25/17.
//  Copyright (c) 2017 Emkukuh. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class Login2Wireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: Login2ViewController) {
        let interactor = Login2Interactor()
        let presenter = Login2Presenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "Login2ViewController") as! Login2ViewController
        configureModule(with: moduleViewController)

        show(moduleViewController, with: transition, animated: animated)
    }
}

// MARK: - Extensions -

extension Login2Wireframe: Login2WireframeInterface {

    func navigate(to option: Login2NavigationOption) {
    }
}
