//
//  Login2Interactor.swift
//  EMFRAME
//
//  Created by Mohammad Kukuh on 8/25/17.
//  Copyright (c) 2017 Emkukuh. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class Login2Interactor {
}

// MARK: - Extensions -

extension Login2Interactor: Login2InteractorInterface {
}
