//
//  Login2Interfaces.swift
//  EMFRAME
//
//  Created by Mohammad Kukuh on 8/25/17.
//  Copyright (c) 2017 Emkukuh. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum Login2NavigationOption {
}

protocol Login2WireframeInterface: WireframeInterface {
    func navigate(to option: Login2NavigationOption)
}

protocol Login2ViewInterface: ViewInterface {
}

protocol Login2PresenterInterface: PresenterInterface {
}

protocol Login2InteractorInterface: InteractorInterface {
}
