//
//  Login2ViewController.swift
//  EMFRAME
//
//  Created by Mohammad Kukuh on 8/25/17.
//  Copyright (c) 2017 Emkukuh. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class Login2ViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: Login2PresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension Login2ViewController: Login2ViewInterface {
}
