//
//  Login2Presenter.swift
//  EMFRAME
//
//  Created by Mohammad Kukuh on 8/25/17.
//  Copyright (c) 2017 Emkukuh. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class Login2Presenter {

    // MARK: - Private properties -

    fileprivate weak var _view: Login2ViewInterface?
    fileprivate var _interactor: Login2InteractorInterface
    fileprivate var _wireframe: Login2WireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: Login2WireframeInterface, view: Login2ViewInterface, interactor: Login2InteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension Login2Presenter: Login2PresenterInterface {
}
